module.exports = {
                content: ["./*.html"],
                darkMode: "class",
                theme: {
                    extend: {
                        colors: {
                            "on-tertiary-container": "#013d4a",
                            "on-error": "#ffffff",
                            "on-background": "#201b0f",
                            error: "#ba1a1a",
                            "on-surface": "#201b0f",
                            "on-tertiary-fixed-variant": "#1a4d5a",
                            "inverse-primary": "#ffb866",
                            "on-secondary-container": "#783603",
                            "on-secondary-fixed-variant": "#753401",
                            "on-tertiary": "#ffffff",
                            "secondary-fixed-dim": "#ffb68c",
                            "on-tertiary-fixed": "#001f27",
                            "inverse-surface": "#363023",
                            "surface-variant": "#ede1ce",
                            "on-primary-fixed": "#2b1700",
                            "surface-container-lowest": "#ffffff",
                            "surface-container": "#f8ecd9",
                            "on-secondary-fixed": "#321200",
                            "inverse-on-surface": "#fbefdc",
                            "primary-fixed-dim": "#ffb866",
                            "on-primary-fixed-variant": "#673d00",
                            surface: "#fff8f2",
                            "on-primary-container": "#513000",
                            "surface-tint": "#875200",
                            "surface-container-low": "#fef2df",
                            "tertiary-fixed": "#baeafa",
                            "surface-container-highest": "#ede1ce",
                            outline: "#867463",
                            "surface-bright": "#fff8f2",
                            "on-error-container": "#93000a",
                            "tertiary-fixed-dim": "#9ecedd",
                            "tertiary-container": "#79a8b7",
                            "secondary-container": "#ffa26a",
                            "on-primary": "#ffffff",
                            secondary: "#934b19",
                            "on-surface-variant": "#534435",
                            "error-container": "#ffdad6",
                            "secondary-fixed": "#ffdbc9",
                            "primary-fixed": "#ffddba",
                            background: "#fff8f2",
                            "surface-container-high": "#f3e7d4",
                            "surface-dim": "#e4d9c6",
                            "on-secondary": "#ffffff",
                            tertiary: "#356572",
                            "primary-container": "#db9130",
                            "outline-variant": "#d9c3af",
                            primary: "#875200",
                        },
                        fontFamily: { headline: ["Space Grotesk"], body: ["Newsreader"], label: ["Work Sans"] },
                        borderRadius: { DEFAULT: "0px", lg: "0px", xl: "0px", full: "9999px" },
                    },
                },
            };
